### ISSUE TITLE
Save feature not working

### ISSUE THREAD

**Issue by akbuga** [Sage-of-Mirrors/WildText#1]
Hello, I want to use your tool to translate to my language, but the saving feature is not working. I wonder if you have a working copy or can you activate the saving feature? Have a nice day.

**Comment by Sage-of-Mirrors** [comment]
Sorry, this tool is pretty much dead. However, I'm told that [Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox) can edit the text files.

**Comment by Sage-of-Mirrors** [comment]
There is also [Msyt](https://gitlab.com/jkcclemens/msyt), which may be a better alternative!

**Comment by akbuga** [comment]
Thanks for quick reply. Switch Toolbox can just show text files and can't handle editing or saving. Myst is a good alternative but the line breaks show with /n and too hard to set line breaks. It would probably be the best text editing program if your application was complete. Your application show color codes, line breaks etc. with clear way. Thanks anyway.
